POST http://localhost:5000/Signup HTTP/1.1
Content-Type: application/json

{
    "email":"",
    "password":"",
    "fullname":" ",
    "phone":""
}
###
GET http://localhost:5000/profile HTTP/1.1
Content-Type: application/json
###
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "email":"ooo@gmail.com",
    "password":""
}

###
POST http://localhost:5000/logout HTTP/1.1
Content-Type: application/json

###
POST http://localhost:5000/Update HTTP/1.1
Content-Type: application/json

{
    "email":"ooo@gmail.com",
    "fullname":"",
    "phone":""
}
